#!/usr/bin/env python3
"""
Inline css/main.css into every page as a <style> block.

Why: an external stylesheet is a render-blocking request. On Slow 4G that
round trip dominates First Contentful Paint. Inlining removes it entirely.

css/main.css REMAINS THE SOURCE OF TRUTH. Edit that file, then run:

    python tools/inline-css.py

The generated block sits between INLINE-CSS:START / END markers and is
replaced wholesale each run, so this is safe to run repeatedly.
"""
import io
import os
import re
import sys
import glob
import hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS = os.path.join(ROOT, 'css', 'main.css')
FONTS = os.path.join(ROOT, 'css', 'fonts.css')  # self-hosted @font-face, prepended
START = '<!-- INLINE-CSS:START (generated by tools/inline-css.py - do not edit) -->'
END = '<!-- INLINE-CSS:END -->'
SKIP_DIRS = ('taste-skill-main', 'skill-main', 'Impeccable-skill', 'templates', 'node_modules')

RE_COMMENT = re.compile(r'/\*.*?\*/', re.S)
RE_WS = re.compile(r'\s+')
RE_PUNCT = re.compile(r'\s*([{}:;,>~+])\s*')
RE_SEMI = re.compile(r';}')
CALC_MASK = 'CALCMASK%dENDCALCMASK'
RE_PARENT_URL = re.compile(r'url\((\s*["\']?)\.\./')


def rebase_urls(css):
    """Rewrite url(../x) to url(/x).

    A relative url() resolves against the STYLESHEET's location. Once the CSS
    is inlined it resolves against the PAGE's location instead, which differs
    per directory depth and breaks at the site root. Root-absolute paths are
    correct from every page.
    """
    return RE_PARENT_URL.sub(lambda m: 'url(' + m.group(1) + '/', css)


def mask_calc(css):
    """Replace every calc(...) span with a placeholder.

    Inside calc(), the + and - operators REQUIRE surrounding whitespace, but
    the punctuation pass strips spaces around + because it is also a sibling
    combinator in selectors. Masking calc spans keeps their spacing intact.
    """
    out = []
    spans = []
    i = 0
    while True:
        j = css.find('calc(', i)
        if j < 0:
            out.append(css[i:])
            break
        out.append(css[i:j])
        depth = 0
        k = j + 4
        while k < len(css):
            if css[k] == '(':
                depth += 1
            elif css[k] == ')':
                depth -= 1
                if depth == 0:
                    k += 1
                    break
            k += 1
        out.append(CALC_MASK % len(spans))
        spans.append(RE_WS.sub(' ', css[j:k]))
        i = k
    return ''.join(out), spans


def minify(css):
    """Conservative minification: strip comments and collapse whitespace."""
    css = rebase_urls(css)
    css = RE_COMMENT.sub('', css)
    css, calcs = mask_calc(css)
    css = RE_WS.sub(' ', css)
    css = RE_PUNCT.sub(lambda m: m.group(1), css)
    css = RE_SEMI.sub('}', css)
    for n, span in enumerate(calcs):
        css = css.replace(CALC_MASK % n, span)
    return css.strip()


def main():
    if not os.path.exists(CSS):
        sys.exit('missing %s' % CSS)
    raw = io.open(CSS, encoding='utf-8').read()
    if os.path.exists(FONTS):
        raw = io.open(FONTS, encoding='utf-8').read() + chr(10) + raw
    mini = minify(raw)

    if mini.count('{') != raw.count('{') or mini.count('{') != mini.count('}'):
        sys.exit('minify produced unbalanced CSS - aborting without writing')
    if '../' in mini:
        sys.exit('relative ../ path survived rebase - aborting without writing')

    block = '%s\n<style>%s</style>\n%s' % (START, mini, END)
    digest = hashlib.sha1(mini.encode('utf-8')).hexdigest()[:8]

    changed = skipped = 0
    for fp in sorted(glob.glob(os.path.join(ROOT, '**', '*.html'), recursive=True)):
        rel = os.path.relpath(fp, ROOT).replace(os.sep, '/')
        if any(rel.startswith(d + '/') or rel == d for d in SKIP_DIRS):
            continue
        s = io.open(fp, encoding='utf-8').read()
        orig = s
        if START in s:
            s = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda m: block, s, flags=re.S)
        else:
            link = re.search(r'[ \t]*<link rel="stylesheet" href="(?:/|(?:\.\./)*)css/main\.css(?:\?[^"]*)?">\n?', s)
            if not link:
                skipped += 1
                continue
            s = s.replace(link.group(0), block + '\n')
        if s != orig:
            io.open(fp, 'w', encoding='utf-8').write(s)
            changed += 1

    print('inlined %d bytes of CSS (sha %s) into %d files' % (len(mini), digest, changed))
    if skipped:
        print('skipped %d file(s) with no stylesheet link' % skipped)


if __name__ == '__main__':
    main()
