// Serves /campbelltown/* from a WordPress install on a different host.
//
// The rest of the site is static assets in this repo and never touches the
// WordPress origin. If the proxy or the origin fails, the catch block falls
// back to the assets so the main site cannot be taken down by this file.
//
// To disconnect WordPress, set WP_ORIGIN back to null. The Worker then answers
// /campbelltown/ with the built-in placeholder and nothing else changes.

const WP_ORIGIN = "wp-origin.drivingschoolliverpool.sydney";
const WP_PREFIX = "/campbelltown";

export default {
  async fetch(request, env) {
    try {
      const url = new URL(request.url);
      const mine =
        url.pathname === WP_PREFIX || url.pathname.startsWith(WP_PREFIX + "/");

      // Everything that is not /campbelltown/* is the static site. Untouched.
      if (!mine) return env.ASSETS.fetch(request);

      if (!WP_ORIGIN) return stageOnePage(url);

      // WordPress is installed at the root of the origin, not in a folder named
      // campbelltown, so the prefix comes off on the way out and goes back on
      // any Location header on the way home.
      const target = new URL(url);
      target.hostname = WP_ORIGIN;
      target.protocol = "https:";
      target.port = "";
      target.pathname = url.pathname.slice(WP_PREFIX.length) || "/";

      const headers = new Headers(request.headers);
      // Let the Host header come from the target URL, or Hostinger serves the
      // wrong vhost.
      headers.delete("host");
      headers.set("X-Forwarded-Host", url.hostname);
      headers.set("X-Forwarded-Proto", "https");

      const upstream = await fetch(
        new Request(target, {
          method: request.method,
          headers: headers,
          body: request.body,
          redirect: "manual",
        })
      );

      // Response(body, upstream) keeps multiple Set-Cookie headers intact,
      // which is what keeps the WordPress login working.
      const res = new Response(upstream.body, upstream);
      const loc = res.headers.get("location");
      if (loc) res.headers.set("location", publicLocation(loc, url.hostname));
      return res;
    } catch (err) {
      // Never take the static site down because this script or the origin failed.
      return env.ASSETS.fetch(request);
    }
  },
};

// Turns an origin-shaped redirect into one the visitor's browser can follow.
// Absolute URLs on the origin get swapped for the public prefix. Root-relative
// paths get the prefix added. Anything already public is left alone.
function publicLocation(loc, host) {
  const publicBase = "https://" + host + WP_PREFIX;

  for (const scheme of ["https://", "http://"]) {
    const originBase = scheme + WP_ORIGIN;
    if (loc.startsWith(originBase)) {
      return publicBase + (loc.slice(originBase.length) || "/");
    }
  }

  if (
    loc.startsWith("/") &&
    loc !== WP_PREFIX &&
    !loc.startsWith(WP_PREFIX + "/")
  ) {
    return WP_PREFIX + loc;
  }

  return loc;
}

function stageOnePage(url) {
  const body =
    "<!doctype html><meta charset=utf-8>" +
    "<meta name=viewport content='width=device-width,initial-scale=1'>" +
    "<meta name=robots content='noindex,nofollow'>" +
    "<title>Campbelltown subfolder test</title>" +
    "<style>body{font:16px/1.6 system-ui,sans-serif;margin:0;padding:40px 20px;" +
    "background:#111;color:#eee}main{max-width:640px;margin:0 auto}" +
    "h1{font-size:24px;margin:0 0 16px}code{background:#222;padding:2px 6px;" +
    "border-radius:3px;font-size:14px}p{color:#bbb}</style>" +
    "<main><h1>Subfolder routing works.</h1>" +
    "<p>This page was generated by the Cloudflare Worker, not served from the " +
    "repository. It proves <code>" + WP_PREFIX + "/</code> can be handed to a " +
    "different origin while the rest of the site stays static.</p>" +
    "<p>Path requested: <code>" + escapeHtml(url.pathname) + "</code><br>" +
    "Generated: <code>" + new Date().toISOString() + "</code></p>" +
    "<p>Next step: set <code>WP_ORIGIN</code> in <code>src/index.js</code> to the " +
    "WordPress host and redeploy.</p></main>";

  return new Response(body, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-robots-tag": "noindex, nofollow",
    },
  });
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
