// Serves /campbelltown/* from somewhere other than this repo.
//
// STAGE 1 (now): WP_ORIGIN is null, so the Worker answers /campbelltown/
// itself with a built-in confirmation page. This proves the routing works
// and, more importantly, proves the rest of the site is unaffected.
//
// STAGE 2 (later): set WP_ORIGIN to the WordPress host, e.g.
//   const WP_ORIGIN = "wp-origin.example.com";
// and the same file reverse-proxies instead. Nothing else changes.

const WP_ORIGIN = null;
const WP_PREFIX = "/campbelltown";

export default {
  async fetch(request, env) {
    try {
      const url = new URL(request.url);
      const mine =
        url.pathname === WP_PREFIX || url.pathname.startsWith(WP_PREFIX + "/");

      // Everything that is not /campbelltown/* is the static site. Untouched.
      if (!mine) return env.ASSETS.fetch(request);

      if (!WP_ORIGIN) return stageOnePage(url);

      const target = new URL(url);
      target.hostname = WP_ORIGIN;
      target.protocol = "https:";
      target.port = "";

      const headers = new Headers(request.headers);
      headers.set("X-Forwarded-Host", url.hostname);
      headers.set("X-Forwarded-Proto", "https");

      const upstream = await fetch(
        new Request(target, {
          method: request.method,
          headers: headers,
          body: request.body,
          redirect: "manual",
        })
      );

      // Response(body, upstream) keeps multiple Set-Cookie headers intact,
      // which is what keeps the WordPress login working.
      const res = new Response(upstream.body, upstream);
      const loc = res.headers.get("location");
      if (loc) {
        res.headers.set(
          "location",
          loc.split("https://" + WP_ORIGIN).join("https://" + url.hostname)
        );
      }
      return res;
    } catch (err) {
      // Never take the static site down because this script or the origin failed.
      return env.ASSETS.fetch(request);
    }
  },
};

function stageOnePage(url) {
  const body =
    "<!doctype html><meta charset=utf-8>" +
    "<meta name=viewport content='width=device-width,initial-scale=1'>" +
    "<meta name=robots content='noindex,nofollow'>" +
    "<title>Campbelltown subfolder test</title>" +
    "<style>body{font:16px/1.6 system-ui,sans-serif;margin:0;padding:40px 20px;" +
    "background:#111;color:#eee}main{max-width:640px;margin:0 auto}" +
    "h1{font-size:24px;margin:0 0 16px}code{background:#222;padding:2px 6px;" +
    "border-radius:3px;font-size:14px}p{color:#bbb}</style>" +
    "<main><h1>Subfolder routing works.</h1>" +
    "<p>This page was generated by the Cloudflare Worker, not served from the " +
    "repository. It proves <code>" + WP_PREFIX + "/</code> can be handed to a " +
    "different origin while the rest of the site stays static.</p>" +
    "<p>Path requested: <code>" + escapeHtml(url.pathname) + "</code><br>" +
    "Generated: <code>" + new Date().toISOString() + "</code></p>" +
    "<p>Next step: set <code>WP_ORIGIN</code> in <code>src/index.js</code> to the " +
    "WordPress host and redeploy.</p></main>";

  return new Response(body, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-robots-tag": "noindex, nofollow",
    },
  });
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
